// Traditional Tambola/Housie number call names
// Format: "Phrase... Number X" (phrase first, then number)
export const TAMBOLA_CALLS = {
  1: "Nelson's Column... Number One",
  2: "One Little Duck... Number Two",
  3: "Cup of Tea... Number Three",
  4: "Knock at the Door... Number Four",
  5: "Man Alive... Number Five",
  6: "Tom Mix... Number Six",
  7: "Lucky Seven... Number Seven",
  8: "Garden Gate... Number Eight",
  9: "Doctor's Orders... Number Nine",
  10: "Downing Street... Number Ten",
  11: "Legs Eleven... Number Eleven",
  12: "One Dozen... Number Twelve",
  13: "Unlucky for Some... Number Thirteen",
  14: "Valentine's Day... Number Fourteen",
  15: "Young and Keen... Number Fifteen",
  16: "Sweet Sixteen... Number Sixteen",
  17: "Dancing Queen... Number Seventeen",
  18: "Coming of Age... Number Eighteen",
  19: "Goodbye Teens... Number Nineteen",
  20: "One Score... Number Twenty",
  21: "Key of the Door... Number Twenty-One",
  22: "Two Little Ducks... Number Twenty-Two",
  23: "Thee and Me... Number Twenty-Three",
  24: "Two Dozen... Number Twenty-Four",
  25: "Duck and Dive... Number Twenty-Five",
  26: "Half a Crown... Number Twenty-Six",
  27: "Gateway to Heaven... Number Twenty-Seven",
  28: "Over Weight... Number Twenty-Eight",
  29: "Rise and Shine... Number Twenty-Nine",
  30: "Dirty Gertie... Number Thirty",
  31: "Get Up and Run... Number Thirty-One",
  32: "Buckle My Shoe... Number Thirty-Two",
  33: "All the Threes... Number Thirty-Three",
  34: "Ask for More... Number Thirty-Four",
  35: "Jump and Jive... Number Thirty-Five",
  36: "Three Dozen... Number Thirty-Six",
  37: "More than Eleven... Number Thirty-Seven",
  38: "Christmas Cake... Number Thirty-Eight",
  39: "Steps... Number Thirty-Nine",
  40: "Life Begins... Number Forty",
  41: "Time for Fun... Number Forty-One",
  42: "Winnie the Pooh... Number Forty-Two",
  43: "Down on Your Knee... Number Forty-Three",
  44: "Droopy Drawers... Number Forty-Four",
  45: "Halfway There... Number Forty-Five",
  46: "Up to Tricks... Number Forty-Six",
  47: "Four and Seven... Number Forty-Seven",
  48: "Four Dozen... Number Forty-Eight",
  49: "PC... Number Forty-Nine",
  50: "Half a Century... Number Fifty",
  51: "Tweak of the Thumb... Number Fifty-One",
  52: "Danny La Rue... Number Fifty-Two",
  53: "Stuck in the Tree... Number Fifty-Three",
  54: "Clean the Floor... Number Fifty-Four",
  55: "Snakes Alive... Number Fifty-Five",
  56: "Was She Worth It... Number Fifty-Six",
  57: "Heinz Varieties... Number Fifty-Seven",
  58: "Make Them Wait... Number Fifty-Eight",
  59: "Brighton Line... Number Fifty-Nine",
  60: "Five Dozen... Number Sixty",
  61: "Baker's Bun... Number Sixty-One",
  62: "Turn the Screw... Number Sixty-Two",
  63: "Tickle Me... Number Sixty-Three",
  64: "Red Raw... Number Sixty-Four",
  65: "Old Age Pension... Number Sixty-Five",
  66: "Clickety Click... Number Sixty-Six",
  67: "Made in Heaven... Number Sixty-Seven",
  68: "Saving Grace... Number Sixty-Eight",
  69: "Either Way Up... Number Sixty-Nine",
  70: "Three Score and Ten... Number Seventy",
  71: "Bang on the Drum... Number Seventy-One",
  72: "Six Dozen... Number Seventy-Two",
  73: "Queen Bee... Number Seventy-Three",
  74: "Candy Store... Number Seventy-Four",
  75: "Strive and Strive... Number Seventy-Five",
  76: "Trombones... Number Seventy-Six",
  77: "Sunset Strip... Number Seventy-Seven",
  78: "Heaven's Gate... Number Seventy-Eight",
  79: "One More Time... Number Seventy-Nine",
  80: "Eight and Blank... Number Eighty",
  81: "Stop and Run... Number Eighty-One",
  82: "Straight on Through... Number Eighty-Two",
  83: "Time for Tea... Number Eighty-Three",
  84: "Seven Dozen... Number Eighty-Four",
  85: "Staying Alive... Number Eighty-Five",
  86: "Between the Sticks... Number Eighty-Six",
  87: "Torquay in Devon... Number Eighty-Seven",
  88: "Two Fat Ladies... Number Eighty-Eight",
  89: "Nearly There... Number Eighty-Nine",
  90: "Top of the Shop... Number Ninety"
};

// Get call name for a number
export const getCallName = (number) => {
  return TAMBOLA_CALLS[number] || `Number ${number}`;
};
