// Traditional Tambola/Housie number call names
export const TAMBOLA_CALLS = {
  1: "Number One - Nelson's Column",
  2: "Number Two - One Little Duck",
  3: "Number Three - Cup of Tea",
  4: "Number Four - Knock at the Door",
  5: "Number Five - Man Alive",
  6: "Number Six - Tom Mix",
  7: "Number Seven - Lucky Seven",
  8: "Number Eight - Garden Gate",
  9: "Number Nine - Doctor's Orders",
  10: "Number Ten - Downing Street",
  11: "Number Eleven - Legs Eleven",
  12: "Number Twelve - One Dozen",
  13: "Number Thirteen - Unlucky for Some",
  14: "Number Fourteen - Valentine's Day",
  15: "Number Fifteen - Young and Keen",
  16: "Number Sixteen - Sweet Sixteen",
  17: "Number Seventeen - Dancing Queen",
  18: "Number Eighteen - Coming of Age",
  19: "Number Nineteen - Goodbye Teens",
  20: "Number Twenty - One Score",
  21: "Number Twenty-One - Key of the Door",
  22: "Number Twenty-Two - Two Little Ducks",
  23: "Number Twenty-Three - Thee and Me",
  24: "Number Twenty-Four - Two Dozen",
  25: "Number Twenty-Five - Duck and Dive",
  26: "Number Twenty-Six - Half a Crown",
  27: "Number Twenty-Seven - Gateway to Heaven",
  28: "Number Twenty-Eight - Over Weight",
  29: "Number Twenty-Nine - Rise and Shine",
  30: "Number Thirty - Dirty Gertie",
  31: "Number Thirty-One - Get Up and Run",
  32: "Number Thirty-Two - Buckle My Shoe",
  33: "Number Thirty-Three - All the Threes",
  34: "Number Thirty-Four - Ask for More",
  35: "Number Thirty-Five - Jump and Jive",
  36: "Number Thirty-Six - Three Dozen",
  37: "Number Thirty-Seven - More than Eleven",
  38: "Number Thirty-Eight - Christmas Cake",
  39: "Number Thirty-Nine - Steps",
  40: "Number Forty - Life Begins",
  41: "Number Forty-One - Time for Fun",
  42: "Number Forty-Two - Winnie the Pooh",
  43: "Number Forty-Three - Down on Your Knee",
  44: "Number Forty-Four - Droopy Drawers",
  45: "Number Forty-Five - Halfway There",
  46: "Number Forty-Six - Up to Tricks",
  47: "Number Forty-Seven - Four and Seven",
  48: "Number Forty-Eight - Four Dozen",
  49: "Number Forty-Nine - PC",
  50: "Number Fifty - Half a Century",
  51: "Number Fifty-One - Tweak of the Thumb",
  52: "Number Fifty-Two - Danny La Rue",
  53: "Number Fifty-Three - Stuck in the Tree",
  54: "Number Fifty-Four - Clean the Floor",
  55: "Number Fifty-Five - Snakes Alive",
  56: "Number Fifty-Six - Was She Worth It",
  57: "Number Fifty-Seven - Heinz Varieties",
  58: "Number Fifty-Eight - Make Them Wait",
  59: "Number Fifty-Nine - Brighton Line",
  60: "Number Sixty - Five Dozen",
  61: "Number Sixty-One - Baker's Bun",
  62: "Number Sixty-Two - Turn the Screw",
  63: "Number Sixty-Three - Tickle Me",
  64: "Number Sixty-Four - Red Raw",
  65: "Number Sixty-Five - Old Age Pension",
  66: "Number Sixty-Six - Clickety Click",
  67: "Number Sixty-Seven - Made in Heaven",
  68: "Number Sixty-Eight - Saving Grace",
  69: "Number Sixty-Nine - Either Way Up",
  70: "Number Seventy - Three Score and Ten",
  71: "Number Seventy-One - Bang on the Drum",
  72: "Number Seventy-Two - Six Dozen",
  73: "Number Seventy-Three - Queen Bee",
  74: "Number Seventy-Four - Candy Store",
  75: "Number Seventy-Five - Strive and Strive",
  76: "Number Seventy-Six - Trombones",
  77: "Number Seventy-Seven - Sunset Strip",
  78: "Number Seventy-Eight - Heaven's Gate",
  79: "Number Seventy-Nine - One More Time",
  80: "Number Eighty - Eight and Blank",
  81: "Number Eighty-One - Stop and Run",
  82: "Number Eighty-Two - Straight on Through",
  83: "Number Eighty-Three - Time for Tea",
  84: "Number Eighty-Four - Seven Dozen",
  85: "Number Eighty-Five - Staying Alive",
  86: "Number Eighty-Six - Between the Sticks",
  87: "Number Eighty-Seven - Torquay in Devon",
  88: "Number Eighty-Eight - Two Fat Ladies",
  89: "Number Eighty-Nine - Nearly There",
  90: "Number Ninety - Top of the Shop"
};

// Get call name for a number
export const getCallName = (number) => {
  return TAMBOLA_CALLS[number] || `Number ${number}`;
};
